monthly_income = input('Enter Your monthly income:')
monthly_expenses = input('Enter your monthly expenses:')
montly_savings = float(monthly_income) - float(monthly_expenses)
projected_savings = montly_savings * 12 + (montly_savings * 12 * 0.05)
print(f'Your monthly savings is {montly_savings}')
print(f'Projected savings after one year, with interest, is: {projected_savings}')